Contact.create!([
  {first_name: "Dylan", last_name: "Wetzel", email: "dylanwetzel@gmail.com", phone_number: "8152767735", middle_name: nil, bio: nil},
  {first_name: "Kyle", last_name: "McConnell", email: "kylemcconnell@gmail.com", phone_number: "5554321234", middle_name: nil, bio: nil},
  {first_name: "Braxton", last_name: "D'Amore", email: "d_braxton_amore@gmail.com", phone_number: "(847) 714-6701 x4239", middle_name: nil, bio: nil},
  {first_name: "Nyah", last_name: "Monahan", email: "nyah_monahan@gmail.com", phone_number: "102.984.0651", middle_name: nil, bio: nil},
  {first_name: "Loyal", last_name: "Muller", email: "muller_loyal@gmail.com", phone_number: "(938) 384-9295 x432", middle_name: nil, bio: nil},
  {first_name: "Frank", last_name: "Veum", email: "frank.veum@gmail.com", phone_number: "1-205-829-2583 x206", middle_name: nil, bio: nil},
  {first_name: "Ivory", last_name: "O'Conner", email: "ivory_conner_o@yahoo.com", phone_number: "813.403.0228 x39525", middle_name: nil, bio: nil},
  {first_name: "Johathan", last_name: "Lebsack", email: "johathan_lebsack@gmail.com", phone_number: "(803) 463-1523 x5480", middle_name: nil, bio: nil},
  {first_name: "Maurine", last_name: "Purdy", email: "purdy.maurine@yahoo.com", phone_number: "(473) 832-0858", middle_name: nil, bio: nil},
  {first_name: "Eveline", last_name: "Lang", email: "lang.eveline@hotmail.com", phone_number: "(130) 413-0289 x151", middle_name: nil, bio: nil},
  {first_name: "Jamie", last_name: "Brekke", email: "jamie_brekke@hotmail.com", phone_number: "1-185-474-1795", middle_name: nil, bio: nil},
  {first_name: "Gaston", last_name: "Casper", email: "gaston_casper@gmail.com", phone_number: "1-449-017-4095", middle_name: nil, bio: nil},
  {first_name: "Jedidiah", last_name: "Kunze", email: "jedidiah.kunze@gmail.com", phone_number: "563-760-2788 x2401", middle_name: nil, bio: nil},
  {first_name: "Amara", last_name: "Kuphal", email: "kuphal_amara@yahoo.com", phone_number: "(373) 858-2126 x43829", middle_name: nil, bio: nil},
  {first_name: "Ashley", last_name: "Oberbrunner", email: "ashley.oberbrunner@gmail.com", phone_number: "588-817-1757", middle_name: nil, bio: nil},
  {first_name: "Martin", last_name: "Turcotte", email: "turcotte.martin@hotmail.com", phone_number: "792.310.4158 x721", middle_name: nil, bio: nil},
  {first_name: "Oma", last_name: "Windler", email: "oma.windler@hotmail.com", phone_number: "872.789.6888", middle_name: nil, bio: nil},
  {first_name: "Jazmyne", last_name: "Abshire", email: "abshire_jazmyne@yahoo.com", phone_number: "1-600-908-7558", middle_name: nil, bio: nil},
  {first_name: "Lexus", last_name: "Wuckert", email: "wuckert.lexus@yahoo.com", phone_number: "118.089.1638 x1090", middle_name: nil, bio: nil},
  {first_name: "Ettie", last_name: "Kozey", email: "ettie.kozey@gmail.com", phone_number: "262-938-2934", middle_name: nil, bio: nil},
  {first_name: "Gilberto", last_name: "Bogisich", email: "gilberto.bogisich@gmail.com", phone_number: "660-397-0456", middle_name: nil, bio: nil},
  {first_name: "Rozella", last_name: "Dooley", email: "dooley_rozella@yahoo.com", phone_number: "720.632.2846 x57931", middle_name: nil, bio: nil},
  {first_name: "Margaret", last_name: "Kshlerin", email: "kshlerin_margaret@hotmail.com", phone_number: "1-784-307-8697", middle_name: nil, bio: nil},
  {first_name: "Lawrence", last_name: "Carroll", email: "carroll.lawrence@gmail.com", phone_number: "1-836-299-6897", middle_name: nil, bio: nil},
  {first_name: "Morris", last_name: "Grant", email: "grant.morris@yahoo.com", phone_number: "1-103-995-6259 x2415", middle_name: nil, bio: nil},
  {first_name: "Leslie", last_name: "Windler", email: "leslie_windler@hotmail.com", phone_number: "(739) 070-2040 x2568", middle_name: nil, bio: nil},
  {first_name: "Johnathan", last_name: "Beahan", email: "johnathan.beahan@yahoo.com", phone_number: "403.669.2067", middle_name: nil, bio: nil},
  {first_name: "Rupert", last_name: "Zieme", email: "zieme.rupert@hotmail.com", phone_number: "(665) 339-6674", middle_name: nil, bio: nil},
  {first_name: "Callie", last_name: "Lueilwitz", email: "lueilwitz_callie@yahoo.com", phone_number: "493.349.3994", middle_name: nil, bio: nil},
  {first_name: "Shana", last_name: "Leannon", email: "shana_leannon@gmail.com", phone_number: "(216) 141-4941 x5475", middle_name: nil, bio: nil},
  {first_name: "Alek", last_name: "Okuneva", email: "alek_okuneva@hotmail.com", phone_number: "625.847.1982 x0065", middle_name: nil, bio: nil},
  {first_name: "Raleigh", last_name: "O'Keefe", email: "keefe_raleigh_o@yahoo.com", phone_number: "1-347-291-1033 x497", middle_name: nil, bio: nil},
  {first_name: "Tiana", last_name: "Okuneva", email: "tiana_okuneva@yahoo.com", phone_number: "(214) 914-2477", middle_name: nil, bio: nil},
  {first_name: "Ashlee", last_name: "Okuneva", email: "ashlee_okuneva@yahoo.com", phone_number: "(146) 046-0779 x166", middle_name: nil, bio: nil},
  {first_name: "Oswaldo", last_name: "Douglas", email: "oswaldo_douglas@hotmail.com", phone_number: "1-326-814-3239", middle_name: nil, bio: nil},
  {first_name: "Estrella", last_name: "Bruen", email: "bruen.estrella@gmail.com", phone_number: "(991) 978-5529 x11511", middle_name: nil, bio: nil},
  {first_name: "Reyes", last_name: "Jaskolski", email: "reyes.jaskolski@yahoo.com", phone_number: "572.567.4029 x899", middle_name: nil, bio: nil},
  {first_name: "Treva", last_name: "Fritsch", email: "fritsch_treva@gmail.com", phone_number: "1-365-595-0218 x6385", middle_name: nil, bio: nil},
  {first_name: "Yesenia", last_name: "Bernier", email: "bernier.yesenia@gmail.com", phone_number: "573-723-1746", middle_name: nil, bio: nil},
  {first_name: "Terrell", last_name: "Armstrong", email: "armstrong_terrell@hotmail.com", phone_number: "718-287-3711", middle_name: nil, bio: nil},
  {first_name: "Lexus", last_name: "Christiansen", email: "lexus_christiansen@yahoo.com", phone_number: "799-791-3985", middle_name: nil, bio: nil},
  {first_name: "Brett", last_name: "Jast", email: "brett.jast@gmail.com", phone_number: "1-806-949-0433 x8954", middle_name: nil, bio: nil},
  {first_name: "Bell", last_name: "Schroeder", email: "schroeder_bell@yahoo.com", phone_number: "882.731.4627 x0313", middle_name: nil, bio: nil},
  {first_name: "Thea", last_name: "Deckow", email: "deckow.thea@gmail.com", phone_number: "(153) 812-3280", middle_name: nil, bio: nil},
  {first_name: "Joaquin", last_name: "Farrell", email: "joaquin_farrell@hotmail.com", phone_number: "1-614-056-9774 x82010", middle_name: nil, bio: nil},
  {first_name: "Mafalda", last_name: "Kshlerin", email: "mafalda_kshlerin@yahoo.com", phone_number: "482-407-3406 x75708", middle_name: nil, bio: nil},
  {first_name: "Thelma", last_name: "Armstrong", email: "thelma_armstrong@yahoo.com", phone_number: "339-174-0029 x789", middle_name: nil, bio: nil},
  {first_name: "Adella", last_name: "Leffler", email: "leffler.adella@hotmail.com", phone_number: "741-867-0635 x21788", middle_name: nil, bio: nil},
  {first_name: "Johann", last_name: "Ryan", email: "johann_ryan@hotmail.com", phone_number: "(460) 635-9686", middle_name: nil, bio: nil},
  {first_name: "Mckayla", last_name: "Monahan", email: "monahan.mckayla@hotmail.com", phone_number: "1-668-259-0350 x362", middle_name: nil, bio: nil},
  {first_name: "Wilber", last_name: "Anderson", email: "wilber_anderson@hotmail.com", phone_number: "1-271-557-0856", middle_name: nil, bio: nil},
  {first_name: "Elvis", last_name: "Swaniawski", email: "swaniawski_elvis@hotmail.com", phone_number: "374.306.4131", middle_name: nil, bio: nil},
  {first_name: "Bonita", last_name: "Hickle", email: "hickle_bonita@hotmail.com", phone_number: "1-930-342-1196 x6918", middle_name: nil, bio: nil},
  {first_name: "Rocio", last_name: "Shanahan", email: "rocio.shanahan@yahoo.com", phone_number: "832.468.2356 x306", middle_name: nil, bio: nil},
  {first_name: "Valerie", last_name: "Wuckert", email: "valerie.wuckert@gmail.com", phone_number: "(848) 338-3915", middle_name: nil, bio: nil},
  {first_name: "Morris", last_name: "Blanda", email: "blanda_morris@gmail.com", phone_number: "(417) 436-8679", middle_name: nil, bio: nil},
  {first_name: "Jeanette", last_name: "Cruickshank", email: "cruickshank.jeanette@gmail.com", phone_number: "938.552.0604 x2966", middle_name: nil, bio: nil},
  {first_name: "Katrina", last_name: "Gleason", email: "katrina.gleason@hotmail.com", phone_number: "1-838-652-1487", middle_name: nil, bio: nil},
  {first_name: "Norbert", last_name: "Koelpin", email: "koelpin.norbert@hotmail.com", phone_number: "1-979-486-3779 x06256", middle_name: nil, bio: nil},
  {first_name: "Reese", last_name: "O'Keefe", email: "o_reese_keefe@hotmail.com", phone_number: "813-030-9988 x751", middle_name: nil, bio: nil},
  {first_name: "Wilson", last_name: "Bartoletti", email: "wilson_bartoletti@yahoo.com", phone_number: "193-155-7837", middle_name: nil, bio: nil},
  {first_name: "Elmer", last_name: "Kiehn", email: "kiehn_elmer@yahoo.com", phone_number: "687.127.3495", middle_name: nil, bio: nil},
  {first_name: "Hallie", last_name: "Nienow", email: "nienow_hallie@yahoo.com", phone_number: "(743) 356-8154 x08948", middle_name: nil, bio: nil},
  {first_name: "Madelynn", last_name: "Schumm", email: "schumm.madelynn@gmail.com", phone_number: "1-975-663-1101", middle_name: nil, bio: nil},
  {first_name: "Roselyn", last_name: "Roob", email: "roselyn.roob@hotmail.com", phone_number: "(422) 424-8840 x33113", middle_name: nil, bio: nil},
  {first_name: "Alexa", last_name: "Rempel", email: "alexa_rempel@yahoo.com", phone_number: "1-501-495-0841 x85482", middle_name: nil, bio: nil},
  {first_name: "Branson", last_name: "Schamberger", email: "schamberger.branson@hotmail.com", phone_number: "(588) 805-3147", middle_name: nil, bio: nil},
  {first_name: "Karina", last_name: "Pfannerstill", email: "karina.pfannerstill@yahoo.com", phone_number: "(254) 331-7173", middle_name: nil, bio: nil},
  {first_name: "Rebeka", last_name: "Erdman", email: "rebeka.erdman@gmail.com", phone_number: "413-315-5280", middle_name: nil, bio: nil},
  {first_name: "Sedrick", last_name: "Haley", email: "haley.sedrick@hotmail.com", phone_number: "(363) 690-1403 x844", middle_name: nil, bio: nil},
  {first_name: "Guadalupe", last_name: "Haley", email: "guadalupe.haley@gmail.com", phone_number: "1-641-718-6034", middle_name: nil, bio: nil},
  {first_name: "Rosalinda", last_name: "Bergnaum", email: "rosalinda_bergnaum@hotmail.com", phone_number: "1-901-610-3775 x843", middle_name: nil, bio: nil},
  {first_name: "Christophe", last_name: "O'Conner", email: "o.christophe.conner@gmail.com", phone_number: "260.372.2704 x7401", middle_name: nil, bio: nil},
  {first_name: "Victor", last_name: "Harris", email: "harris.victor@gmail.com", phone_number: "(401) 199-9590", middle_name: nil, bio: nil},
  {first_name: "Leanne", last_name: "Koch", email: "leanne_koch@gmail.com", phone_number: "123-910-2987 x429", middle_name: nil, bio: nil},
  {first_name: "Ignatius", last_name: "Lueilwitz", email: "lueilwitz_ignatius@yahoo.com", phone_number: "(103) 928-4378", middle_name: nil, bio: nil},
  {first_name: "Tremayne", last_name: "Hessel", email: "hessel_tremayne@gmail.com", phone_number: "(536) 649-2282", middle_name: nil, bio: nil},
  {first_name: "Sabina", last_name: "Dare", email: "sabina_dare@hotmail.com", phone_number: "285.319.2896 x85372", middle_name: nil, bio: nil},
  {first_name: "Keshaun", last_name: "Reinger", email: "keshaun.reinger@hotmail.com", phone_number: "678.799.9695 x12887", middle_name: nil, bio: nil},
  {first_name: "Marquise", last_name: "Beatty", email: "marquise.beatty@hotmail.com", phone_number: "1-332-381-9646", middle_name: nil, bio: nil},
  {first_name: "Maxine", last_name: "Tillman", email: "maxine_tillman@gmail.com", phone_number: "1-402-503-0398 x2716", middle_name: nil, bio: nil},
  {first_name: "Holden", last_name: "Feest", email: "holden.feest@yahoo.com", phone_number: "1-794-490-3006 x08608", middle_name: nil, bio: nil},
  {first_name: "Jody", last_name: "Tromp", email: "tromp.jody@yahoo.com", phone_number: "1-704-382-6505", middle_name: nil, bio: nil},
  {first_name: "Pasquale", last_name: "Rodriguez", email: "rodriguez.pasquale@yahoo.com", phone_number: "197-396-5348 x1538", middle_name: nil, bio: nil},
  {first_name: "Eula", last_name: "Lindgren", email: "lindgren.eula@hotmail.com", phone_number: "1-173-228-0338", middle_name: nil, bio: nil},
  {first_name: "Duane", last_name: "Fahey", email: "fahey_duane@hotmail.com", phone_number: "(104) 565-2498", middle_name: nil, bio: nil},
  {first_name: "Vena", last_name: "Mayert", email: "vena.mayert@yahoo.com", phone_number: "451-452-1272", middle_name: nil, bio: nil},
  {first_name: "Jaron", last_name: "O'Conner", email: "jaron_o_conner@gmail.com", phone_number: "953.704.2814", middle_name: nil, bio: nil},
  {first_name: "Cortney", last_name: "Jacobson", email: "jacobson.cortney@gmail.com", phone_number: "122.737.1850 x2914", middle_name: nil, bio: nil},
  {first_name: "Greg", last_name: "Koepp", email: "koepp.greg@yahoo.com", phone_number: "1-310-100-1713", middle_name: nil, bio: nil},
  {first_name: "Samson", last_name: "Abbott", email: "abbott_samson@hotmail.com", phone_number: "(294) 694-3931 x42374", middle_name: nil, bio: nil},
  {first_name: "Wade", last_name: "Turner", email: "turner.wade@yahoo.com", phone_number: "802.360.7148", middle_name: nil, bio: nil},
  {first_name: "Lenore", last_name: "Bartell", email: "bartell.lenore@yahoo.com", phone_number: "1-222-362-0063", middle_name: nil, bio: nil},
  {first_name: "Murl", last_name: "Senger", email: "senger_murl@gmail.com", phone_number: "(890) 857-9158 x4117", middle_name: nil, bio: nil},
  {first_name: "Sanford", last_name: "Macejkovic", email: "sanford_macejkovic@hotmail.com", phone_number: "377.396.8365 x0909", middle_name: nil, bio: nil},
  {first_name: "Stacy", last_name: "Runolfsdottir", email: "stacy.runolfsdottir@yahoo.com", phone_number: "666-751-3882 x8701", middle_name: nil, bio: nil},
  {first_name: "Jalon", last_name: "O'Keefe", email: "keefe.o.jalon@hotmail.com", phone_number: "1-817-339-2205 x34616", middle_name: nil, bio: nil},
  {first_name: "Judd", last_name: "Rogahn", email: "rogahn_judd@yahoo.com", phone_number: "244.461.3329", middle_name: nil, bio: nil},
  {first_name: "Josue", last_name: "Fritsch", email: "josue.fritsch@gmail.com", phone_number: "313-166-6623 x3715", middle_name: nil, bio: nil},
  {first_name: "Felton", last_name: "Koelpin", email: "koelpin.felton@yahoo.com", phone_number: "535.687.2188", middle_name: nil, bio: nil},
  {first_name: "Alexie", last_name: "Labadie", email: "alexie_labadie@yahoo.com", phone_number: "1-247-310-4016 x40254", middle_name: nil, bio: nil},
  {first_name: "Jaydon", last_name: "Yundt", email: "jaydon_yundt@gmail.com", phone_number: "365-568-2894", middle_name: nil, bio: nil},
  {first_name: "Frankie", last_name: "McWetzel", email: "frankiemcwetzel@gmail.com", phone_number: "555-555-5555", middle_name: nil, bio: nil},
  {first_name: "Frankie", last_name: "McWetzel", email: "frankiemcwetzel@gmail.com", phone_number: "555-555-5555", middle_name: nil, bio: nil},
  {first_name: "Frankie", last_name: "McWetzel", email: "frankiemcwetzel@gmail.com", phone_number: "555-555-5555", middle_name: nil, bio: nil},
  {first_name: "Frankie", last_name: "McWetzel", email: "herherher", phone_number: "8888888888", middle_name: nil, bio: nil},
  {first_name: "Brittany", last_name: "Wetzel", email: "brittanywetzel@gmail.com", phone_number: "8155551212", middle_name: nil, bio: nil},
  {first_name: "Brittany", last_name: "Wetzel", email: "brittanywetzel@gmail.com", phone_number: "8155551212", middle_name: "Hope", bio: "laskdjfalskdfjalskdjflaksdjflaskdjflakdsjflaksdjflaksdjf"},
  {first_name: "asdf", last_name: "asdf", email: "asdf", phone_number: "asdf", middle_name: "asdf", bio: "asdf"}
])
